added the ability to install a package with dependencies

diff --git a/pkg-get.in b/pkg-get.in
--- a/pkg-get.in
+++ b/pkg-get.in
@@ -24,6 +24,7 @@ SIGNIFY_PATH=${SIGNIFY_PATH:-"/etc/pkg-get"}
 SIGNIFY_NAME="pkg-get"
 COMPRESSION="gz"
 PORT_SUFFIX=".pkg.tar.${COMPRESSION}"
+PRTGET="/usr/bin/prt-get"
 PKGADD="/usr/bin/pkgadd"
 
 WORK_DIR=$(mktemp -d)
@@ -38,6 +39,39 @@ message() {
     # parametr 1 - text message
     MESSAGE="$1"
     printf '|\e[1;33mwarn\x1B[0m| \e[0;32m%-12s\x1B[0m %s\n' "$ACTION" "$MESSAGE"
+}
+
+gen_packages_install(){
+    local package="$1"
+
+    PACKAGES=( $(echo "$status" | grep -e "^\[\s\].*" | cut -d ']' -f2- | tac -s ' ') )
+
+    for pkg in ${PACKAGES[@]}; do
+        local package_path=$($PRTGET path $pkg)
+        local port=$(echo $package_path | rev | cut -d '/' -f2 | rev)
+        local version=$(source $package_path/Pkgfile ; echo $version)
+        local release=$(source $package_path/Pkgfile ; echo $release)
+        if [[ ! -z ${version} ]]; then
+            echo $port $pkg ${version}-${release} >> $WORK_DIR/ports.diff
+        fi
+    done
+}
+
+check_install() {
+    local package="$1"
+
+    status=$($PRTGET isinst $package)
+
+    if [[ $status != *not*installed ]]; then
+        echo "$status"
+    else
+        status=$($PRTGET deptree $package)
+        if [[ $status == *not*found ]]; then
+            echo "$status"
+        else
+            gen_packages_install "$package"
+        fi
+    fi
 }
 
 check_for_updates() {
@@ -75,17 +109,20 @@ verify_sign() {
         if [[ ! $($SIGNIFY -p "${SIGNIFY_PATH}/${SIGNIFY_NAME}.pub" -V -x "${IRRADIUM_CACHE}/${port}/${pkg}.sig" -m "${IRRADIUM_CACHE}/${port}/${pkg}" 2>&1 > /dev/null) ]]; then
             echo "OK:  port: ${port}    signature package: ${pkg}"
             # update package
-            local pkgadd=$($PKGADD -u "${IRRADIUM_CACHE}/${port}/${pkg}")
-            if [[ -z $pkgadd ]]; then
-                echo "OK:  port: ${port}    update package: ${pkg}"
-            else
-                echo "ERROR:  port: ${port}    update package: ${pkg}"
-            fi
+#            local pkgadd=$($PKGADD -u "${IRRADIUM_CACHE}/${port}/${pkg}")
+#            if [[ -z $pkgadd ]]; then
+#                echo "OK:  port: ${port}    update package: ${pkg}"
+#            else
+#                echo "ERROR:  port: ${port}    update package: ${pkg}"
+#            fi
+            return 0
         else
             echo "ERROR:  port: ${port}    signature package: ${pkg}"
+            return 1
         fi
     else
         echo "ERROR:  port: ${port}    signature missing: ${pkg}.sig"
+        return 1
     fi
 }
 
@@ -143,6 +180,9 @@ prepare_ports() {
                 downloads ${port##*-} $name $version
             elif [[ $type == "verify" ]]; then
                 verify_sign ${port##*-} ${name}'#'${version}${PORT_SUFFIX}
+                if [[ "$?" != 1 ]]; then
+                    echo "${IRRADIUM_CACHE}/${port##*-}/${name}#${version}${PORT_SUFFIX}" >> $WORK_DIR/update
+                fi
             fi
         done < $WORK_DIR/ports.diff
     fi
@@ -167,11 +207,13 @@ usage() {
     echo
     echo "usage: $COMMAND [options]"
     echo "options:"
-    echo "   -s, --sign [path]   sign files"
-    echo "   -u, --update        update packages"
-    echo "   -c, --clear         clearing cache"
-    echo "   -v, --version       print version and exit"
-    echo "   -h, --help          print help and exit"
+    echo "   -s,  --sign [path]   sign files"
+    echo "   -i,  --install       install package"
+    echo "   -di, --depinst       install packages and their dependencies"
+    echo "   -u,  --update        update packages"
+    echo "   -c,  --clear         clearing cache"
+    echo "   -v,  --version       print version and exit"
+    echo "   -h,  --help          print help and exit"
     echo
 }
 
@@ -183,6 +225,10 @@ parse_options() {
         case "$OPT" in
         -s|--sign)
             OPT_MODE="sign" ;;
+        -i|--install)
+            OPT_MODE="install" ;;
+        -di|--depinst)
+            OPT_MODE="depinst" ;;
         -u|--update)
             OPT_MODE="update" ;;
         -c|--clear)
@@ -219,6 +265,12 @@ main() {
 
     if [[ $OPT_MODE == "sign" && ( ! -z $OPT_COLLECTIONS && -d ${OPT_COLLECTIONS/[[:space:]]/} ) ]]; then
         sign_files ${OPT_COLLECTIONS/[[:space:]]/}
+    fi
+
+    if [[ $OPT_MODE == "install"  && ! -z ${OPT_COLLECTIONS/[[:space:]]/} ]]; then
+        check_install ${OPT_COLLECTIONS/[[:space:]]/}
+        prepare_ports "download"
+        prepare_ports "verify"
     fi
 
     if [[ $OPT_MODE == "update" ]]; then
